version: "3"
services:
    app:
        build:
            context: ./
        ports:
            - 3000:3000
        depends_on: 
            - database
    database:
        build:
            context: ./db/
        ports:
            - 5432:5432